
name: Revisar secretos

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  escaneo:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Preparar configuración
        run: cp trufflehog.yaml /tmp/trufflehog.yaml

      - name: Buscar secretos
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --config=/tmp/trufflehog.yaml --results=verified,unknown,unverified
