name: Revisar secretos
on:
  push:
    branches: [main]
    permissions:
      contents: read
    jobs:
      escaneo:
        runs-on: ubuntu-latest
        steps:
            uses: actions/checkout@v4
        with:
          fetch-depth: 0
            - name: Buscar secretos
          uses: trufflesecurity/trufflehog@main
          with:
            extra_args: --config=/tmp/trufflehog.yaml --results=verified,unknown,unverified